name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      # - name: Install Expo CLI
      #   run: npm install --global expo-cli

      # - name: Install Dependencies
      #   run: npm install
      #   working-directory: ./frontend/linkr

      # - name: Build Expo App
      #   run: expo build:android --release-channel build-1-${{ github.run_id }}
      #   working-directory: ./frontend/linkr

      # - name: Archive Build
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: android-app-1
      #     path: ~/expo-app/android/app/build/outputs/bundle/release
  
  
  # build-2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Install Node.js and NPM
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16

  #     - name: Install Expo CLI
  #       run: npm install --global expo-cli

  #     - name: Install Dependencies
  #       run: npm install
  #       working-directory: ./frontend/linkr
        
  #     - name: Build Expo App
  #       run: expo build:android --release-channel build-2-${{ github.run_id }}
  #       working-directory: ./frontend/linkr

  #     - name: Archive Build
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: android-app-2
  #         path: ~/expo-app/android/app/build/outputs/bundle/release

  # diffoscope:
  #   needs: [build-1, build-2]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Install Diffoscope
  #       run: sudo apt-get update && sudo apt-get install -y diffoscope

  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: android-app-1
  #         path: ./frontend/linkr/build-1

  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: android-app-2
  #         path: ./frontend/linkr/build-2

  #     - name: Compare Artifacts
  #       run: diffoscope ~/build-1/app-release.apk ~/build-2/app-release.apk > diffoscope.log

