name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-1:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Install Expo CLI
        run: npm install --global expo-cli
      
      - name: Install eas
        run: npm install -g eas-cli

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend/project

      - name: Build Expo App
        run: eas build -p android 
        working-directory: ./frontend/project

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: android-app-1
          path: ~/expo-app/android/app/build/outputs/bundle/release
  
  
  build-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Expo CLI
        run: npm install --global expo-cli
      
      - name: Install eas
        run: npm install -g eas-cli

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend/project
        
      - name: Build Expo App
        run: eas build -p android  
        working-directory: ./frontend/project

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: android-app-2
          path: ~/expo-app/android/app/build/outputs/bundle/release

  diffoscope:
    needs: [build-1, build-2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Diffoscope
        run: sudo apt-get update && sudo apt-get install -y diffoscope

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: android-app-1
          path: /expo-app/android/app/build/outputs/bundle/release

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: android-app-2
          path: /expo-app/android/app/build/outputs/bundle/release

      - name: Compare Artifacts
        run: diffoscope ~/build-1/app-release.apk ~/build-2/app-release.apk > diffoscope.log

