name: Expo build

on: [push, pull_request]

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Expo CLI
        run: npm install --global expo-cli

      - name: Install Dependencies
        run: npm install

      - name: Build Expo App
        run: expo build:android --release-channel build-1-${{ github.run_id }}

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: android-app-1
          path: ~/expo-app/android/app/build/outputs/bundle/release
  
  
  build-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Expo CLI
        run: npm install --global expo-cli

      - name: Install Dependencies
        run: npm install

      - name: Build Expo App
        run: expo build:android --release-channel build-2-${{ github.run_id }}

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: android-app-2
          path: ~/expo-app/android/app/build/outputs/bundle/release

  diffoscope:
    needs: [build-1, build-2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Diffoscope
        run: sudo apt-get update && sudo apt-get install -y diffoscope

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: android-app-1
          path: ~/build-1

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: android-app-2
          path: ~/build-2

      - name: Compare Artifacts
        run: diffoscope ~/build-1/app-release.apk ~/build-2/app-release.apk > diffoscope.log

